// Industry (ICP) catalog presets — the starter products / services / assemblies
// every new tenant is pre-populated with. Minimum 12 items per industry, each
// with an accurate CAD wholesale unit cost (your COGS), a sensible markup, the
// right unit of measure, and an image. Customer price is computed automatically
// from cost × (1 + markup%). Assemblies roll up their component items.
//
// Costs are grounded in 2024–2025 Canadian wholesale/contractor pricing; the
// description notes the rough USD-equivalent where useful. Numbers are starting
// points a tenant can fine-tune — never blank, never a guess presented as fact.

export type CatalogPresetKind = "service" | "product" | "assembly";

export type CatalogPresetItem = {
  /** Stable key within the industry — also used to wire assembly components. */
  key: string;
  kind: CatalogPresetKind;
  name: string;
  sku: string;
  category: string;
  description: string;
  unit: string;
  /** Your wholesale / COGS cost per unit, in CAD. Ignored for assemblies (rolled up). */
  unitCost: number;
  /** % markup over cost (auto price mode). Ignored for assemblies (rolled up). */
  markupPct: number;
  taxable: boolean;
  /** Assembly composition by component `key` + qty. */
  components?: { key: string; qty: number }[];
  /** Image search slug used at seed time to resolve a hosted image URL. */
  imageQuery: string;
  /** Resolved hosted image URL (filled in below; may be "" until sourced). */
  image: string;
};

export type CatalogPreset = Record<string, CatalogPresetItem[]>;

// NOTE: image URLs are filled in progressively via the asset pipeline. An empty
// string is safe — the catalog UI simply shows a placeholder tile.
export const CATALOG_PRESETS: CatalogPreset = {
  // ───────────────────────── HVAC ─────────────────────────
  hvac: [
    { key: "diagnostic", kind: "service", name: "Diagnostic / Service Call", sku: "HVAC-DIAG", category: "Service", unit: "job", unitCost: 45, markupPct: 110, taxable: true, imageQuery: "hvac technician diagnostic service call", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F1dG7W6-3ZBZVTLTAxFtC2%2Fhvac-technician-diagnostic-service-call_1.jpg", description: "Flat-rate trip + system diagnosis. Applied to repair if work proceeds. (~$70 USD)" },
    { key: "labor", kind: "service", name: "HVAC Labor (per hour)", sku: "HVAC-LBR", category: "Labor", unit: "hour", unitCost: 55, markupPct: 100, taxable: true, imageQuery: "hvac technician working on furnace", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F2E0g4ITU_55ia0JQEjC3H%2Fhvac-technician-working-on-furnace_3.jpg", description: "Standard skilled technician labor rate, billed hourly. (~$80 USD)" },
    { key: "tuneup", kind: "service", name: "Seasonal Tune-Up", sku: "HVAC-TUNE", category: "Maintenance", unit: "job", unitCost: 60, markupPct: 130, taxable: true, imageQuery: "hvac maintenance tune up technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FFN3pqT2y_xGpsEOPVsQOC%2Fhvac-maintenance-tune-up-technician_1.jpg", description: "Multi-point clean & inspect for furnace or AC. (~$105 USD price)" },
    { key: "capacitor", kind: "product", name: "Run Capacitor (dual 45/5 µF)", sku: "HVAC-CAP", category: "Parts", unit: "each", unitCost: 14, markupPct: 220, taxable: true, imageQuery: "hvac dual run capacitor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FWpXQLZgsODQszLoppSY0n%2Fhvac-dual-run-capacitor_8.jpg", description: "Common dual-run capacitor for condenser fan + compressor. (~$10 USD cost)" },
    { key: "contactor", kind: "product", name: "Contactor (40A, 24V coil)", sku: "HVAC-CONT", category: "Parts", unit: "each", unitCost: 22, markupPct: 180, taxable: true, imageQuery: "hvac contactor 40 amp", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FsP_DhWfaDrCt63a1X1OaI%2Fhvac-contactor-40-amp_0.jpg", description: "Definite-purpose contactor for condensing units. (~$16 USD cost)" },
    { key: "blower", kind: "product", name: "Blower Motor (1/2 HP ECM)", sku: "HVAC-BLWR", category: "Parts", unit: "each", unitCost: 230, markupPct: 70, taxable: true, imageQuery: "hvac blower motor ecm", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FIftN-BXVxlWMQXbaHOLOV%2Fhvac-blower-motor-ecm_3.jpg", description: "Variable-speed ECM blower motor replacement. (~$170 USD cost)" },
    { key: "thermostat", kind: "product", name: "Smart Thermostat (Wi-Fi)", sku: "HVAC-TSTAT", category: "Controls", unit: "each", unitCost: 130, markupPct: 60, taxable: true, imageQuery: "smart wifi thermostat", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FGHqE7Sx1_QPQfO5DHt6yP%2Fsmart-wifi-thermostat_7.jpg", description: "Programmable Wi-Fi thermostat (Ecobee/Nest class). (~$95 USD cost)" },
    { key: "filter", kind: "product", name: "Pleated Air Filter (16×25×1)", sku: "HVAC-FLT", category: "Consumables", unit: "each", unitCost: 6, markupPct: 150, taxable: true, imageQuery: "pleated hvac air filter", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FIted8VVajk4zS6r_OsOxQ%2Fpleated-hvac-air-filter_6.jpg", description: "MERV 11 pleated filter. (~$4.50 USD cost)" },
    { key: "furnace", kind: "product", name: "Gas Furnace (96% AFUE, 60k BTU)", sku: "HVAC-FURN", category: "Equipment", unit: "each", unitCost: 1850, markupPct: 45, taxable: true, imageQuery: "high efficiency gas furnace unit", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FHKyVbTa20ernxlMGk1oCA%2Fhigh-efficiency-gas-furnace-unit_6.png", description: "High-efficiency two-stage residential furnace. (~$1,350 USD cost)" },
    { key: "condenser", kind: "product", name: "AC Condenser (2.5 ton, 14 SEER2)", sku: "HVAC-COND", category: "Equipment", unit: "each", unitCost: 1750, markupPct: 45, taxable: true, imageQuery: "air conditioner condenser unit outdoor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F9OrmCFp_3qxkV2kuVyLkf%2Fair-conditioner-condenser-unit-outdoor_1.jpg", description: "Outdoor condensing unit, 2.5 ton residential. (~$1,300 USD cost)" },
    { key: "asm-furnace-install", kind: "assembly", name: "Furnace Supply & Install", sku: "HVAC-ASM-FURN", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "furnace installation technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FeSUyARHz9s9xIMJjQejLK%2Ffurnace-installation-technician_4.jpg", description: "Turn-key high-efficiency furnace replacement: unit, thermostat, filter + labor.", components: [{ key: "furnace", qty: 1 }, { key: "thermostat", qty: 1 }, { key: "filter", qty: 1 }, { key: "labor", qty: 6 }] },
    { key: "asm-ac-install", kind: "assembly", name: "AC Supply & Install", sku: "HVAC-ASM-AC", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "air conditioner installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4zeudOIrcLaC-jYOch9vr%2Fair-conditioner-installation_0.jpg", description: "Complete central AC install: condenser, contactor, capacitor + labor.", components: [{ key: "condenser", qty: 1 }, { key: "contactor", qty: 1 }, { key: "capacitor", qty: 1 }, { key: "labor", qty: 5 }] },
  ],

  // ─────────────────────── PLUMBING ───────────────────────
  plumbing: [
    { key: "diagnostic", kind: "service", name: "Service Call / Diagnosis", sku: "PLM-DIAG", category: "Service", unit: "job", unitCost: 45, markupPct: 110, taxable: true, imageQuery: "plumber service call diagnosis", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fjr4ncwpFtpvXYUfkYoLPy%2Fplumber-service-call-diagnosis_5.jpg", description: "Trip charge + leak/fault diagnosis. (~$70 USD)" },
    { key: "labor", kind: "service", name: "Plumbing Labor (per hour)", sku: "PLM-LBR", category: "Labor", unit: "hour", unitCost: 55, markupPct: 100, taxable: true, imageQuery: "plumber working under sink", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FziITCcxLLKugUoZqkWT43%2Fplumber-working-under-sink_1.jpg", description: "Licensed plumber hourly labor. (~$80 USD)" },
    { key: "drain", kind: "service", name: "Drain Cleaning / Snaking", sku: "PLM-DRN", category: "Service", unit: "job", unitCost: 50, markupPct: 200, taxable: true, imageQuery: "drain cleaning auger plumbing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FktjlHhAztJum7mcjkm7m9%2Fdrain-cleaning-auger-plumbing_1.jpg", description: "Mechanical auger drain clearing, single fixture. (~$150 USD price)" },
    { key: "wax", kind: "product", name: "Toilet Wax Ring Kit", sku: "PLM-WAX", category: "Parts", unit: "each", unitCost: 5, markupPct: 200, taxable: true, imageQuery: "toilet wax ring kit", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F5jNH9VpJFcuYFW0TMFpuX%2Ftoilet-wax-ring-kit_0.jpg", description: "Wax ring + bolts for toilet reseat. (~$3.50 USD cost)" },
    { key: "supply", kind: "product", name: "Braided Supply Line (1/2 in)", sku: "PLM-SUP", category: "Parts", unit: "each", unitCost: 7, markupPct: 170, taxable: true, imageQuery: "braided water supply line plumbing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fznov7H3W--LABFe6nj951%2Fbraided-water-supply-line-plumbing_1.jpg", description: "Stainless braided flexible supply line. (~$5 USD cost)" },
    { key: "shutoff", kind: "product", name: "Quarter-Turn Shutoff Valve", sku: "PLM-VLV", category: "Parts", unit: "each", unitCost: 9, markupPct: 160, taxable: true, imageQuery: "quarter turn shutoff valve plumbing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F84oM1cHwCgDelFQJiry9N%2Fquarter-turn-shutoff-valve-plumbing_1.jpg", description: "1/4-turn angle stop valve. (~$6.50 USD cost)" },
    { key: "faucet", kind: "product", name: "Kitchen Faucet (single-handle)", sku: "PLM-FCT", category: "Fixtures", unit: "each", unitCost: 95, markupPct: 70, taxable: true, imageQuery: "single handle kitchen faucet", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FT0ZOej4_nK-eMou5qthD6%2Fsingle-handle-kitchen-faucet_5.png", description: "Pull-down single-handle kitchen faucet. (~$70 USD cost)" },
    { key: "toilet", kind: "product", name: "Two-Piece Toilet (1.28 GPF)", sku: "PLM-TLT", category: "Fixtures", unit: "each", unitCost: 180, markupPct: 60, taxable: true, imageQuery: "two piece toilet white", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FAMH9zz6FhPlOLCUR-InmD%2Ftwo-piece-toilet-white_1.jpg", description: "Water-efficient elongated toilet. (~$135 USD cost)" },
    { key: "heater", kind: "product", name: "Water Heater (50 gal gas)", sku: "PLM-WH", category: "Equipment", unit: "each", unitCost: 1100, markupPct: 50, taxable: true, imageQuery: "tank water heater 50 gallon gas", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FbeCiNC7dBBX_pEjeFifCq%2Ftank-water-heater-50-gallon-gas_2.jpg", description: "50-gallon atmospheric-vent natural gas water heater. (~$820 USD cost)" },
    { key: "sump", kind: "product", name: "Sump Pump (1/3 HP)", sku: "PLM-SUMP", category: "Equipment", unit: "each", unitCost: 145, markupPct: 65, taxable: true, imageQuery: "submersible sump pump", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fe68eHDBtZZnQeA1fBi1Ff%2Fsubmersible-sump-pump_0.jpg", description: "Cast-iron submersible sump pump. (~$108 USD cost)" },
    { key: "asm-wh-install", kind: "assembly", name: "Water Heater Supply & Install", sku: "PLM-ASM-WH", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "water heater installation plumber", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FaT7htJ-pgGXFm1j-0w-vK%2Fwater-heater-installation-plumber_3.jpg", description: "Remove & replace tank water heater: unit, supply lines, shutoff + labor.", components: [{ key: "heater", qty: 1 }, { key: "supply", qty: 2 }, { key: "shutoff", qty: 1 }, { key: "labor", qty: 4 }] },
    { key: "asm-toilet-install", kind: "assembly", name: "Toilet Supply & Install", sku: "PLM-ASM-TLT", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "toilet installation bathroom", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F8ib8luDy0KIoGpnOxasJU%2Ftoilet-installation-bathroom_8.jpg", description: "New toilet set: bowl, wax ring, supply line + labor.", components: [{ key: "toilet", qty: 1 }, { key: "wax", qty: 1 }, { key: "supply", qty: 1 }, { key: "labor", qty: 1.5 }] },
  ],

  // ────────────────────── ELECTRICAL ──────────────────────
  electrical: [
    { key: "diagnostic", kind: "service", name: "Service Call / Troubleshoot", sku: "ELE-DIAG", category: "Service", unit: "job", unitCost: 50, markupPct: 110, taxable: true, imageQuery: "electrician troubleshooting panel", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fjzvf2R-_LqOfxDUdtZ_EU%2Felectrician-troubleshooting-panel_7.jpg", description: "Trip + fault-finding diagnosis. (~$75 USD)" },
    { key: "labor", kind: "service", name: "Electrician Labor (per hour)", sku: "ELE-LBR", category: "Labor", unit: "hour", unitCost: 60, markupPct: 100, taxable: true, imageQuery: "electrician working wiring", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FPUlEerYW7KMKjsR7BxgYg%2Felectrician-working-wiring_5.jpg", description: "Licensed electrician hourly labor. (~$88 USD)" },
    { key: "inspection", kind: "service", name: "Electrical Safety Inspection", sku: "ELE-INSP", category: "Service", unit: "job", unitCost: 65, markupPct: 130, taxable: true, imageQuery: "electrical inspection home", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F3Yr7uknSZMHuVf9SJz1iI%2Felectrical-inspection-home_6.jpg", description: "Whole-home safety inspection + report. (~$110 USD price)" },
    { key: "receptacle", kind: "product", name: "Tamper-Resistant Receptacle", sku: "ELE-RCP", category: "Parts", unit: "each", unitCost: 3, markupPct: 200, taxable: true, imageQuery: "electrical outlet receptacle white", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FfilvyvY8d-1BF2Kp9keQe%2Felectrical-outlet-receptacle-white_0.jpg", description: "15A TR duplex receptacle. (~$2.20 USD cost)" },
    { key: "gfci", kind: "product", name: "GFCI Receptacle (20A)", sku: "ELE-GFCI", category: "Parts", unit: "each", unitCost: 18, markupPct: 130, taxable: true, imageQuery: "gfci outlet receptacle", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FFykqCtwd58k1ArNeAndCa%2Fgfci-outlet-receptacle_0.jpg", description: "20A GFCI protected receptacle. (~$13 USD cost)" },
    { key: "breaker", kind: "product", name: "Circuit Breaker (single-pole 20A)", sku: "ELE-BRK", category: "Parts", unit: "each", unitCost: 12, markupPct: 150, taxable: true, imageQuery: "circuit breaker single pole", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FiHwNdb9cRI-04C2in5kp5%2Fcircuit-breaker-single-pole_1.jpg", description: "Standard single-pole breaker. (~$9 USD cost)" },
    { key: "wire", kind: "product", name: "NMD90 Wire 14/2 (per ft)", sku: "ELE-WIRE", category: "Materials", unit: "ft", unitCost: 0.9, markupPct: 120, taxable: true, imageQuery: "electrical romex wire roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FO7LkOmhi4IkQpHeQzySgm%2Felectrical-romex-wire-roll_1.jpg", description: "Copper NMD90 14/2 building wire. (~$0.66 USD/ft cost)" },
    { key: "led", kind: "product", name: "LED Recessed Light (6 in)", sku: "ELE-LED", category: "Fixtures", unit: "each", unitCost: 14, markupPct: 110, taxable: true, imageQuery: "led recessed pot light", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FMlNH7t0Uq9tzBXfcLscVs%2Fled-recessed-pot-light_4.jpg", description: "Dimmable 6-inch LED pot light. (~$10 USD cost)" },
    { key: "panel", kind: "product", name: "Main Breaker Panel (100A, 24-space)", sku: "ELE-PNL", category: "Equipment", unit: "each", unitCost: 165, markupPct: 70, taxable: true, imageQuery: "electrical breaker panel load center", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FKN3YrWpNWYmjuksbYs94T%2Felectrical-breaker-panel-load-center_1.jpg", description: "100A indoor main breaker load centre. (~$122 USD cost)" },
    { key: "evcharger", kind: "product", name: "EV Charger (Level 2, 40A)", sku: "ELE-EVC", category: "Equipment", unit: "each", unitCost: 520, markupPct: 50, taxable: true, imageQuery: "level 2 ev charger wall", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FlxSIa8LWI_gS5Fuv5PGcI%2Flevel-2-ev-charger-wall_1.jpg", description: "Hardwired 40A Level-2 EV charging station. (~$385 USD cost)" },
    { key: "asm-panel-upgrade", kind: "assembly", name: "100A Panel Upgrade", sku: "ELE-ASM-PNL", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "electrical panel upgrade installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FSVQNzBAwfC9vdVn2ZQEia%2Felectrical-panel-upgrade-installation_2.jpg", description: "Service panel replacement: panel, breakers, wire + labor + inspection.", components: [{ key: "panel", qty: 1 }, { key: "breaker", qty: 8 }, { key: "wire", qty: 40 }, { key: "labor", qty: 8 }, { key: "inspection", qty: 1 }] },
    { key: "asm-ev-install", kind: "assembly", name: "EV Charger Install", sku: "ELE-ASM-EV", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "ev charger installation garage", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F__f_7xD2E5zqmTvBTUY8Q%2Fev-charger-installation-garage_4.jpg", description: "Level-2 EV charger install: charger, breaker, wire + labor.", components: [{ key: "evcharger", qty: 1 }, { key: "breaker", qty: 1 }, { key: "wire", qty: 30 }, { key: "labor", qty: 4 }] },
  ],

  // ──────────────── RESTORATION & EMERGENCY ────────────────
  restoration: [
    { key: "assessment", kind: "service", name: "Emergency Assessment", sku: "RST-ASMT", category: "Service", unit: "job", unitCost: 60, markupPct: 130, taxable: true, imageQuery: "water damage assessment inspector", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FxvBmAHONhDvxxoDJFBDt1%2Fwater-damage-assessment-inspector_0.jpg", description: "Rapid on-site damage assessment + moisture mapping. (~$140 USD price)" },
    { key: "labor", kind: "service", name: "Restoration Labor (per hour)", sku: "RST-LBR", category: "Labor", unit: "hour", unitCost: 50, markupPct: 100, taxable: true, imageQuery: "restoration worker cleanup", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FznwZJ0nBac09grENEZaWP%2Frestoration-worker-cleanup_6.jpg", description: "Mitigation/remediation technician hourly labor. (~$74 USD)" },
    { key: "waterextract", kind: "service", name: "Water Extraction (per sq ft)", sku: "RST-EXT", category: "Mitigation", unit: "sqft", unitCost: 0.6, markupPct: 150, taxable: true, imageQuery: "water extraction flood cleanup", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F-tY-irKbLUuKQYx4fm39c%2Fwater-extraction-flood-cleanup_8.jpg", description: "Standing-water extraction, per sq ft affected. (~$0.45 USD/sqft cost)" },
    { key: "antimicrobial", kind: "product", name: "Antimicrobial Treatment (gal)", sku: "RST-AMB", category: "Consumables", unit: "gal", unitCost: 28, markupPct: 90, taxable: true, imageQuery: "antimicrobial disinfectant jug", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FIuqaPJRrvufYt_ot1f2CB%2Fantimicrobial-disinfectant-jug_3.jpg", description: "EPA-registered antimicrobial/disinfectant. (~$21 USD/gal cost)" },
    { key: "polysheet", kind: "product", name: "6-mil Poly Containment (roll)", sku: "RST-POLY", category: "Materials", unit: "roll", unitCost: 42, markupPct: 80, taxable: true, imageQuery: "plastic sheeting containment roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FYnD8_95fbANNQJhqiX76E%2Fplastic-sheeting-containment-roll_6.jpg", description: "10×100 ft 6-mil poly for containment barriers. (~$31 USD cost)" },
    { key: "airmover", kind: "product", name: "Air Mover / Blower (rental-day)", sku: "RST-AIR", category: "Equipment", unit: "each", unitCost: 12, markupPct: 200, taxable: true, imageQuery: "air mover blower drying fan", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FXA-wjfOIg43wYKqh7XgNP%2Fair-mover-blower-drying-fan_0.jpg", description: "Centrifugal air mover, charged per unit per day. (~$9 USD/day cost)" },
    { key: "dehumidifier", kind: "product", name: "LGR Dehumidifier (rental-day)", sku: "RST-DEH", category: "Equipment", unit: "each", unitCost: 35, markupPct: 170, taxable: true, imageQuery: "lgr commercial dehumidifier", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FJFbD9ZPGLT1T-hpPgZAmZ%2Flgr-commercial-dehumidifier_0.jpg", description: "Low-grain refrigerant dehumidifier, per day. (~$26 USD/day cost)" },
    { key: "airscrubber", kind: "product", name: "HEPA Air Scrubber (rental-day)", sku: "RST-SCR", category: "Equipment", unit: "each", unitCost: 40, markupPct: 160, taxable: true, imageQuery: "hepa air scrubber negative air machine", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F67hwAq3D6aSw1kBd3rul2%2Fhepa-air-scrubber-negative-air-machine_0.jpg", description: "HEPA air scrubber/negative-air machine, per day. (~$30 USD/day cost)" },
    { key: "ppe", kind: "product", name: "PPE Kit (Tyvek + respirator)", sku: "RST-PPE", category: "Consumables", unit: "set", unitCost: 22, markupPct: 90, taxable: true, imageQuery: "tyvek suit respirator ppe", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FgVW9jjRBWujGncNyrxtBv%2Ftyvek-suit-respirator-ppe_3.jpg", description: "Tyvek suit, gloves, half-mask respirator + filters. (~$16 USD cost)" },
    { key: "boardup", kind: "service", name: "Emergency Board-Up", sku: "RST-BRD", category: "Mitigation", unit: "job", unitCost: 90, markupPct: 120, taxable: true, imageQuery: "emergency board up window plywood", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4UBdmhyQnVSZovc1nDbyD%2Femergency-board-up-window-plywood_0.jpg", description: "Secure openings with plywood after loss event. (~$200 USD price)" },
    { key: "asm-water-mit", kind: "assembly", name: "Water Mitigation (avg room)", sku: "RST-ASM-WTR", category: "Mitigation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "water mitigation drying equipment room", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FCVL7yxRmXBXHj-_eU0mdM%2Fwater-mitigation-drying-equipment-room_0.jpg", description: "3-day average-room dry-out: extraction, movers, dehu, treatment + labor.", components: [{ key: "waterextract", qty: 200 }, { key: "airmover", qty: 9 }, { key: "dehumidifier", qty: 3 }, { key: "antimicrobial", qty: 1 }, { key: "labor", qty: 6 }] },
    { key: "asm-mold-remed", kind: "assembly", name: "Mold Remediation (contained)", sku: "RST-ASM-MLD", category: "Remediation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "mold remediation containment worker", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fvklfc3RXO5wMq4BN_RJj7%2Fmold-remediation-containment-worker_0.jpg", description: "Contained remediation: poly barrier, scrubber, PPE, antimicrobial + labor.", components: [{ key: "polysheet", qty: 1 }, { key: "airscrubber", qty: 3 }, { key: "ppe", qty: 2 }, { key: "antimicrobial", qty: 2 }, { key: "labor", qty: 10 }] },
  ],

  // ────────────── APPLIANCE REPAIR & HOME SVC ──────────────
  appliance: [
    { key: "diagnostic", kind: "service", name: "Diagnostic Visit", sku: "APP-DIAG", category: "Service", unit: "job", unitCost: 40, markupPct: 120, taxable: true, imageQuery: "appliance repair technician diagnostic", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F1zIw95WtLKAQUHJuS2s53%2Fappliance-repair-technician-diagnostic_6.png", description: "Trip + fault diagnosis, credited to repair. (~$65 USD price)" },
    { key: "labor", kind: "service", name: "Repair Labor (per hour)", sku: "APP-LBR", category: "Labor", unit: "hour", unitCost: 48, markupPct: 100, taxable: true, imageQuery: "appliance repair technician working", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FmWQG0UPYB0VuRhuPPFMQ9%2Fappliance-repair-technician-working_2.jpg", description: "Appliance repair technician hourly labor. (~$70 USD)" },
    { key: "install", kind: "service", name: "Appliance Installation", sku: "APP-INST", category: "Service", unit: "job", unitCost: 45, markupPct: 130, taxable: true, imageQuery: "appliance installation kitchen", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FaqDi8KmjCM0Li2G_whW60%2Fappliance-installation-kitchen_0.jpg", description: "Standard hook-up/installation of one appliance. (~$105 USD price)" },
    { key: "fridge-comp", kind: "product", name: "Refrigerator Compressor", sku: "APP-RCMP", category: "Parts", unit: "each", unitCost: 135, markupPct: 80, taxable: true, imageQuery: "refrigerator compressor part", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FoteeTX_gHS1yAUCYLTfF7%2Frefrigerator-compressor-part_7.jpg", description: "OEM-equivalent fridge compressor. (~$100 USD cost)" },
    { key: "heating-element", kind: "product", name: "Dryer Heating Element", sku: "APP-DHE", category: "Parts", unit: "each", unitCost: 32, markupPct: 110, taxable: true, imageQuery: "dryer heating element coil", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FAX_whk5hHuRlVTFsD6UIb%2Fdryer-heating-element-coil_2.jpg", description: "Replacement dryer heating element. (~$24 USD cost)" },
    { key: "drain-pump", kind: "product", name: "Washer Drain Pump", sku: "APP-WDP", category: "Parts", unit: "each", unitCost: 45, markupPct: 95, taxable: true, imageQuery: "washing machine drain pump", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FLYcnWL4FaMeJDW1n_eSiG%2Fwashing-machine-drain-pump_0.jpg", description: "Washing-machine drain pump assembly. (~$33 USD cost)" },
    { key: "ice-maker", kind: "product", name: "Ice Maker Assembly", sku: "APP-ICE", category: "Parts", unit: "each", unitCost: 78, markupPct: 85, taxable: true, imageQuery: "refrigerator ice maker assembly", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fd7U0jFS3ZvltAVAKni3ox%2Frefrigerator-ice-maker-assembly_4.jpg", description: "Modular ice maker assembly. (~$58 USD cost)" },
    { key: "thermostat", kind: "product", name: "Oven Thermostat / Sensor", sku: "APP-OTS", category: "Parts", unit: "each", unitCost: 28, markupPct: 110, taxable: true, imageQuery: "oven temperature sensor part", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FT9wGG8s5YmBRmdqiA8RFc%2Foven-temperature-sensor-part_0.jpg", description: "Oven temperature sensor/thermostat. (~$21 USD cost)" },
    { key: "door-gasket", kind: "product", name: "Door Gasket / Seal", sku: "APP-GSK", category: "Parts", unit: "each", unitCost: 38, markupPct: 95, taxable: true, imageQuery: "refrigerator door gasket seal", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FcmgntAgtOGqQs33ivHdJf%2Frefrigerator-door-gasket-seal_0.jpg", description: "Fridge/oven door gasket seal. (~$28 USD cost)" },
    { key: "control-board", kind: "product", name: "Electronic Control Board", sku: "APP-ECB", category: "Parts", unit: "each", unitCost: 110, markupPct: 75, taxable: true, imageQuery: "appliance control board pcb", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FNpyCh7nvSh34YWjxovX-8%2Fappliance-control-board-pcb_2.jpg", description: "Main electronic control board. (~$82 USD cost)" },
    { key: "asm-fridge-repair", kind: "assembly", name: "Refrigerator Repair (compressor)", sku: "APP-ASM-RFR", category: "Repair", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "refrigerator repair technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FOm-n188-2vvI5bZ414BMl%2Frefrigerator-repair-technician_5.jpg", description: "Compressor replacement: part + labor + diagnostic.", components: [{ key: "fridge-comp", qty: 1 }, { key: "labor", qty: 2 }, { key: "diagnostic", qty: 1 }] },
    { key: "asm-dryer-repair", kind: "assembly", name: "Dryer No-Heat Repair", sku: "APP-ASM-DRY", category: "Repair", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "dryer repair technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FMl3YREfxtXjCIz4-4UWOo%2Fdryer-repair-technician_0.jpg", description: "No-heat fix: heating element + labor + diagnostic.", components: [{ key: "heating-element", qty: 1 }, { key: "labor", qty: 1.5 }, { key: "diagnostic", qty: 1 }] },
  ],

  // ─────────────── COURIER & DELIVERY ───────────────
  courier: [
    { key: "local-delivery", kind: "service", name: "Local Delivery (per stop)", sku: "CUR-LCL", category: "Delivery", unit: "each", unitCost: 6, markupPct: 130, taxable: true, imageQuery: "courier delivery van package", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FAPS1K8GXi5ilJ57FSA93g%2Fcourier-delivery-van-package_6.jpg", description: "Standard same-city delivery per drop. (~$14 USD price)" },
    { key: "rush", kind: "service", name: "Rush / Same-Hour Delivery", sku: "CUR-RSH", category: "Delivery", unit: "each", unitCost: 12, markupPct: 160, taxable: true, imageQuery: "rush courier urgent delivery", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F5Ccvj6BQfi-hf3hMrFfg9%2Frush-courier-urgent-delivery_3.jpg", description: "Priority same-hour dispatch. (~$31 USD price)" },
    { key: "mileage", kind: "service", name: "Distance Surcharge (per km)", sku: "CUR-KM", category: "Delivery", unit: "each", unitCost: 0.4, markupPct: 100, taxable: true, imageQuery: "delivery route map distance", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FmMzqVaV5l3NoJABaPMGOd%2Fdelivery-route-map-distance_4.jpg", description: "Per-km surcharge beyond base zone. (~$0.30 USD/km cost)" },
    { key: "wait", kind: "service", name: "Wait Time (per 15 min)", sku: "CUR-WAIT", category: "Service", unit: "each", unitCost: 5, markupPct: 120, taxable: true, imageQuery: "delivery driver waiting", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FReEZOn3tYqJu2SvQkfy_J%2Fdelivery-driver-waiting_3.jpg", description: "Driver wait time, billed per 15 minutes. (~$11 USD price)" },
    { key: "labor", kind: "service", name: "Driver / Handler (per hour)", sku: "CUR-LBR", category: "Labor", unit: "hour", unitCost: 24, markupPct: 90, taxable: true, imageQuery: "delivery driver loading van", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FwZT9Crvo-42EpeS7iG99g%2Fdelivery-driver-loading-van_0.jpg", description: "Dedicated driver/handler hourly rate. (~$36 USD price)" },
    { key: "small-box", kind: "product", name: "Small Shipping Box", sku: "CUR-BOXS", category: "Packaging", unit: "each", unitCost: 0.8, markupPct: 150, taxable: true, imageQuery: "small cardboard shipping box", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fuwr0W15uJz5nF0SOrACdO%2Fsmall-cardboard-shipping-box_0.jpg", description: "Single-wall small carton. (~$0.60 USD cost)" },
    { key: "large-box", kind: "product", name: "Large Shipping Box", sku: "CUR-BOXL", category: "Packaging", unit: "each", unitCost: 2.2, markupPct: 140, taxable: true, imageQuery: "large cardboard shipping box", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FRB0a5OhmklhHEynikyZyv%2Flarge-cardboard-shipping-box_5.jpg", description: "Double-wall large carton. (~$1.65 USD cost)" },
    { key: "bubble", kind: "product", name: "Bubble Wrap (per ft)", sku: "CUR-BUB", category: "Packaging", unit: "ft", unitCost: 0.25, markupPct: 160, taxable: true, imageQuery: "bubble wrap roll packaging", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F9DIj3XVXzdB5svhS5qPKn%2Fbubble-wrap-roll-packaging_3.jpg", description: "Protective bubble wrap, per foot. (~$0.19 USD/ft cost)" },
    { key: "pallet", kind: "product", name: "Wooden Pallet (standard)", sku: "CUR-PLT", category: "Packaging", unit: "each", unitCost: 14, markupPct: 90, taxable: true, imageQuery: "wooden shipping pallet", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FjWJAL-uEC_SWoxfyScdcJ%2Fwooden-shipping-pallet_0.jpg", description: "Standard 48×40 shipping pallet. (~$10 USD cost)" },
    { key: "stretchwrap", kind: "product", name: "Stretch Wrap (roll)", sku: "CUR-STR", category: "Packaging", unit: "roll", unitCost: 9, markupPct: 110, taxable: true, imageQuery: "stretch pallet wrap roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FSXMnZSEyEI2gmN2tx8Y1j%2Fstretch-pallet-wrap-roll_0.jpg", description: "Pallet stretch-wrap film roll. (~$6.70 USD cost)" },
    { key: "asm-pallet-ship", kind: "assembly", name: "Palletized Freight Drop", sku: "CUR-ASM-PLT", category: "Delivery", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "palletized freight delivery forklift", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FnA8qsQj2uAZryshCiBizA%2Fpalletized-freight-delivery-forklift_0.jpg", description: "Palletized freight delivery: pallet, wrap, handling + delivery.", components: [{ key: "pallet", qty: 1 }, { key: "stretchwrap", qty: 1 }, { key: "labor", qty: 1 }, { key: "local-delivery", qty: 1 }] },
    { key: "asm-fragile-rush", kind: "assembly", name: "Fragile Rush Parcel", sku: "CUR-ASM-FRG", category: "Delivery", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "fragile package handling courier", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F9ayfKCj5MCpGgvQjGrOQc%2Ffragile-package-handling-courier_4.jpg", description: "Protected rush parcel: box, bubble wrap + rush delivery.", components: [{ key: "large-box", qty: 1 }, { key: "bubble", qty: 6 }, { key: "rush", qty: 1 }] },
  ],

  // ─────────────── SECURITY & ALARM ───────────────
  security: [
    { key: "assessment", kind: "service", name: "Security Site Assessment", sku: "SEC-ASMT", category: "Service", unit: "job", unitCost: 55, markupPct: 130, taxable: true, imageQuery: "security consultant site assessment", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F0GcFBySZkzGzQiMm-NXvF%2Fsecurity-consultant-site-assessment_2.jpg", description: "On-site risk assessment + system design. (~$125 USD price)" },
    { key: "labor", kind: "service", name: "Installer Labor (per hour)", sku: "SEC-LBR", category: "Labor", unit: "hour", unitCost: 52, markupPct: 100, taxable: true, imageQuery: "security system installer working", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FKmgP0X2qJNPtNMQGevrlH%2Fsecurity-system-installer-working_6.jpg", description: "Certified alarm installer hourly labor. (~$77 USD)" },
    { key: "monitoring", kind: "service", name: "24/7 Monitoring (per month)", sku: "SEC-MON", category: "Recurring", unit: "each", unitCost: 8, markupPct: 250, taxable: true, imageQuery: "alarm monitoring center", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4gtdr0qxoUMDCzaAcpm4G%2Falarm-monitoring-center_2.jpg", description: "Central-station monitoring, monthly. (~$28 USD price)" },
    { key: "panel", kind: "product", name: "Alarm Control Panel", sku: "SEC-PNL", category: "Equipment", unit: "each", unitCost: 120, markupPct: 80, taxable: true, imageQuery: "alarm control panel keypad", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FiDp-VEGjE-QNFfzCbdEsF%2Falarm-control-panel-keypad_4.png", description: "Wireless alarm control panel + keypad. (~$90 USD cost)" },
    { key: "door-sensor", kind: "product", name: "Door / Window Sensor", sku: "SEC-DWS", category: "Devices", unit: "each", unitCost: 9, markupPct: 160, taxable: true, imageQuery: "door window contact sensor alarm", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FtG5XebHpVIY6RLyidnaCS%2Fdoor-window-contact-sensor-alarm_3.jpg", description: "Wireless magnetic contact sensor. (~$6.70 USD cost)" },
    { key: "motion", kind: "product", name: "Motion Detector (PIR)", sku: "SEC-PIR", category: "Devices", unit: "each", unitCost: 16, markupPct: 140, taxable: true, imageQuery: "pir motion detector sensor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FrGfEiz06QxujzqNykYGIk%2Fpir-motion-detector-sensor_6.jpg", description: "Pet-immune PIR motion sensor. (~$12 USD cost)" },
    { key: "camera", kind: "product", name: "IP Security Camera (4MP)", sku: "SEC-CAM", category: "Devices", unit: "each", unitCost: 65, markupPct: 90, taxable: true, imageQuery: "ip security camera dome", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FEiZ-7rCe28IzmGuDXJWC5%2Fip-security-camera-dome_0.jpg", description: "4MP PoE dome camera, night vision. (~$48 USD cost)" },
    { key: "nvr", kind: "product", name: "NVR Recorder (8-channel)", sku: "SEC-NVR", category: "Equipment", unit: "each", unitCost: 180, markupPct: 70, taxable: true, imageQuery: "nvr network video recorder", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FRUedsgui_tH1LTub9X1f_%2Fnvr-network-video-recorder_1.jpg", description: "8-channel PoE NVR with 2TB storage. (~$135 USD cost)" },
    { key: "keypad", kind: "product", name: "Smart Door Lock / Keypad", sku: "SEC-LOCK", category: "Devices", unit: "each", unitCost: 95, markupPct: 75, taxable: true, imageQuery: "smart door lock keypad", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fn6W_VgUW6cQ0LPxf9CAR_%2Fsmart-door-lock-keypad_5.jpg", description: "Connected keypad smart lock. (~$70 USD cost)" },
    { key: "siren", kind: "product", name: "Outdoor Siren / Strobe", sku: "SEC-SIR", category: "Devices", unit: "each", unitCost: 34, markupPct: 110, taxable: true, imageQuery: "outdoor alarm siren strobe", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Ff-1148WV8dq29viFlsKeg%2Foutdoor-alarm-siren-strobe_1.jpg", description: "Weatherproof siren + strobe. (~$25 USD cost)" },
    { key: "asm-alarm-pkg", kind: "assembly", name: "Home Alarm Starter Package", sku: "SEC-ASM-ALM", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "home alarm system installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FGfs3gRbTkuh7me30NZocL%2Fhome-alarm-system-installation_2.jpg", description: "Panel + 3 door sensors + motion + siren installed.", components: [{ key: "panel", qty: 1 }, { key: "door-sensor", qty: 3 }, { key: "motion", qty: 1 }, { key: "siren", qty: 1 }, { key: "labor", qty: 4 }] },
    { key: "asm-camera-pkg", kind: "assembly", name: "4-Camera Surveillance System", sku: "SEC-ASM-CAM", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "cctv camera system installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FabbArwsbhUToJB8UWB2tF%2Fcctv-camera-system-installation_0.jpg", description: "NVR + 4 cameras installed and configured.", components: [{ key: "nvr", qty: 1 }, { key: "camera", qty: 4 }, { key: "labor", qty: 6 }] },
  ],

  // ─────────────── TELECOM INSTALLERS ───────────────
  telecom: [
    { key: "sitesurvey", kind: "service", name: "Site Survey", sku: "TEL-SRV", category: "Service", unit: "job", unitCost: 45, markupPct: 120, taxable: true, imageQuery: "telecom site survey technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FvGI8Zzu9GaUr4efBV_vW5%2Ftelecom-site-survey-technician_1.jpg", description: "Pre-install signal/site survey. (~$100 USD price)" },
    { key: "labor", kind: "service", name: "Install Labor (per hour)", sku: "TEL-LBR", category: "Labor", unit: "hour", unitCost: 50, markupPct: 100, taxable: true, imageQuery: "telecom technician installing cable", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F2-ZwJJmVfdNnSJsE-XHNW%2Ftelecom-technician-installing-cable_2.jpg", description: "Telecom installer hourly labor. (~$74 USD)" },
    { key: "activation", kind: "service", name: "Service Activation", sku: "TEL-ACT", category: "Service", unit: "job", unitCost: 30, markupPct: 130, taxable: true, imageQuery: "internet service activation router", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fw_m8AkRIjDmgDlfOVSrP0%2Finternet-service-activation-router_3.jpg", description: "Provision + activate subscriber service. (~$70 USD price)" },
    { key: "cat6", kind: "product", name: "Cat6 Cable (per ft)", sku: "TEL-CAT6", category: "Cabling", unit: "ft", unitCost: 0.35, markupPct: 130, taxable: true, imageQuery: "cat6 ethernet cable spool", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FowvuTvpFurNHWZPEu7jXV%2Fcat6-ethernet-cable-spool_5.jpg", description: "Riser-rated Cat6 cable, per foot. (~$0.26 USD/ft cost)" },
    { key: "fiber", kind: "product", name: "Fiber Drop Cable (per ft)", sku: "TEL-FIB", category: "Cabling", unit: "ft", unitCost: 0.55, markupPct: 130, taxable: true, imageQuery: "fiber optic drop cable", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FqmX6KyR-InmTc9ikOm8bX%2Ffiber-optic-drop-cable_0.jpg", description: "Single-mode fiber drop, per foot. (~$0.41 USD/ft cost)" },
    { key: "keystone", kind: "product", name: "RJ45 Keystone Jack", sku: "TEL-KEY", category: "Parts", unit: "each", unitCost: 1.2, markupPct: 180, taxable: true, imageQuery: "rj45 keystone jack", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FQCR0pP8F3mRsoW8UeqWtM%2Frj45-keystone-jack_0.jpg", description: "Cat6 keystone jack. (~$0.90 USD cost)" },
    { key: "wallplate", kind: "product", name: "Wall Plate (2-port)", sku: "TEL-WP", category: "Parts", unit: "each", unitCost: 2.5, markupPct: 150, taxable: true, imageQuery: "ethernet wall plate 2 port", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FnP60Zf-l3hp-MHKve6W21%2Fethernet-wall-plate-2-port_0.jpg", description: "Dual-port keystone wall plate. (~$1.85 USD cost)" },
    { key: "router", kind: "product", name: "Wi-Fi 6 Router / Gateway", sku: "TEL-RTR", category: "Equipment", unit: "each", unitCost: 110, markupPct: 70, taxable: true, imageQuery: "wifi 6 router gateway", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FcTX8UCmHasqPd9iGY659M%2Fwifi-6-router-gateway_8.jpg", description: "Dual-band Wi-Fi 6 gateway. (~$82 USD cost)" },
    { key: "ont", kind: "product", name: "Fiber ONT / Modem", sku: "TEL-ONT", category: "Equipment", unit: "each", unitCost: 85, markupPct: 70, taxable: true, imageQuery: "fiber ont modem", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fa326aoT-T5E7Uapod5o-Q%2Ffiber-ont-modem_2.jpg", description: "GPON optical network terminal. (~$63 USD cost)" },
    { key: "ap", kind: "product", name: "Wireless Access Point", sku: "TEL-AP", category: "Equipment", unit: "each", unitCost: 95, markupPct: 75, taxable: true, imageQuery: "wireless access point ceiling", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FU6TOhmyA9xlEBvcUtX_ej%2Fwireless-access-point-ceiling_4.jpg", description: "PoE ceiling-mount Wi-Fi access point. (~$70 USD cost)" },
    { key: "asm-fiber-install", kind: "assembly", name: "Fiber Internet Install", sku: "TEL-ASM-FIB", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "fiber internet installation home", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FrNf42_lmDeqoVKkd1zjbU%2Ffiber-internet-installation-home_1.jpg", description: "Fiber drop install: cable, ONT, router, activation + labor.", components: [{ key: "fiber", qty: 100 }, { key: "ont", qty: 1 }, { key: "router", qty: 1 }, { key: "activation", qty: 1 }, { key: "labor", qty: 3 }] },
    { key: "asm-network-drop", kind: "assembly", name: "Structured Cable Drop", sku: "TEL-ASM-DROP", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "ethernet cable drop installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FWSl2FjnhQP_-MHjy2zia9%2Fethernet-cable-drop-installation_2.jpg", description: "Single Cat6 drop: cable, jack, wall plate + labor.", components: [{ key: "cat6", qty: 60 }, { key: "keystone", qty: 2 }, { key: "wallplate", qty: 1 }, { key: "labor", qty: 1.5 }] },
  ],

  // ─────────────── ROOFING CONTRACTORS ───────────────
  roofing: [
    { key: "inspection", kind: "service", name: "Roof Inspection", sku: "ROF-INSP", category: "Service", unit: "job", unitCost: 50, markupPct: 130, taxable: true, imageQuery: "roof inspection contractor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F0zq-g7-E5LKSfdQVNqR4Z%2Froof-inspection-contractor_2.jpg", description: "Full roof inspection + condition report. (~$115 USD price)" },
    { key: "labor", kind: "service", name: "Roofing Labor (per hour)", sku: "ROF-LBR", category: "Labor", unit: "hour", unitCost: 45, markupPct: 100, taxable: true, imageQuery: "roofer working on roof", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FoCStHQ4kwnBYoC-R3QA64%2Froofer-working-on-roof_0.jpg", description: "Roofing crew hourly labor (per worker). (~$66 USD)" },
    { key: "teardown", kind: "service", name: "Tear-Off / Disposal (per sq)", sku: "ROF-TEAR", category: "Service", unit: "each", unitCost: 35, markupPct: 110, taxable: true, imageQuery: "roof tear off shingle removal", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FzvxQNHLSeybEMue8uH-Me%2Froof-tear-off-shingle-removal_4.jpg", description: "Remove + dispose old roofing, per roofing square (100 sq ft). (~$74 USD price)" },
    { key: "shingles", kind: "product", name: "Architectural Shingles (per sq)", sku: "ROF-SHG", category: "Materials", unit: "each", unitCost: 110, markupPct: 60, taxable: true, imageQuery: "architectural asphalt shingles bundle", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fz7SDIbc3BZBWMuBieJYKj%2Farchitectural-asphalt-shingles-bundle_1.jpg", description: "Laminated architectural shingles, per square (3 bundles). (~$82 USD cost)" },
    { key: "underlayment", kind: "product", name: "Synthetic Underlayment (roll)", sku: "ROF-UND", category: "Materials", unit: "roll", unitCost: 78, markupPct: 55, taxable: true, imageQuery: "synthetic roof underlayment roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FX8abLzUsmb0VXP_K0CJwI%2Fsynthetic-roof-underlayment-roll_1.jpg", description: "10 sq synthetic underlayment roll. (~$58 USD cost)" },
    { key: "iceshield", kind: "product", name: "Ice & Water Shield (roll)", sku: "ROF-ICE", category: "Materials", unit: "roll", unitCost: 95, markupPct: 55, taxable: true, imageQuery: "ice and water shield membrane roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FHebWevGB_zBc71sqLFG99%2Fice-and-water-shield-membrane-roll_0.jpg", description: "Self-adhered ice & water membrane, 2 sq. (~$70 USD cost)" },
    { key: "dripedge", kind: "product", name: "Aluminum Drip Edge (10 ft)", sku: "ROF-DRP", category: "Materials", unit: "each", unitCost: 9, markupPct: 90, taxable: true, imageQuery: "aluminum drip edge roofing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F9cwJnPxKupZR7veJeVvyf%2Faluminum-drip-edge-roofing_3.jpg", description: "10-ft aluminum drip-edge flashing. (~$6.70 USD cost)" },
    { key: "ridgevent", kind: "product", name: "Ridge Vent (4 ft)", sku: "ROF-RDG", category: "Materials", unit: "each", unitCost: 14, markupPct: 90, taxable: true, imageQuery: "roof ridge vent", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FST4kQTlqx_qNkyvPL4UJx%2Froof-ridge-vent_8.jpg", description: "4-ft rolled ridge ventilation. (~$10 USD cost)" },
    { key: "boot", kind: "product", name: "Pipe Boot Flashing", sku: "ROF-BOOT", category: "Materials", unit: "each", unitCost: 8, markupPct: 110, taxable: true, imageQuery: "roof pipe boot flashing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FOOEoKh2X2WyELWs1scbs-%2Froof-pipe-boot-flashing_6.png", description: "Rubber pipe-boot roof flashing. (~$6 USD cost)" },
    { key: "nails", kind: "product", name: "Roofing Nails (box)", sku: "ROF-NAIL", category: "Consumables", unit: "box", unitCost: 22, markupPct: 80, taxable: true, imageQuery: "roofing coil nails box", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fz2-af0TCttrUhIksIXpbV%2Froofing-coil-nails-box_0.jpg", description: "Coil roofing nails, 7,200/box. (~$16 USD cost)" },
    { key: "asm-reroof", kind: "assembly", name: "Re-Roof (per square, installed)", sku: "ROF-ASM-RE", category: "Installation", unit: "each", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "asphalt shingle roof installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FsnNqjeBoFTge9aMBRBz_I%2Fasphalt-shingle-roof-installation_5.jpg", description: "Installed re-roof per square: tear-off, underlayment, shingles, accessories + labor.", components: [{ key: "teardown", qty: 1 }, { key: "underlayment", qty: 0.1 }, { key: "shingles", qty: 1 }, { key: "dripedge", qty: 1.2 }, { key: "nails", qty: 0.1 }, { key: "labor", qty: 2.5 }] },
    { key: "asm-leak-repair", kind: "assembly", name: "Roof Leak Repair", sku: "ROF-ASM-LK", category: "Repair", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "roof leak repair flashing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FCBz7iQbBvw0018kSEBIVK%2Froof-leak-repair-flashing_0.jpg", description: "Targeted leak repair: flashing, boot, shingles + labor + inspection.", components: [{ key: "boot", qty: 1 }, { key: "shingles", qty: 0.2 }, { key: "labor", qty: 2 }, { key: "inspection", qty: 1 }] },
  ],

  // ───────── PROPERTY MAINTENANCE & LANDSCAPING ─────────
  landscaping: [
    { key: "mowing", kind: "service", name: "Lawn Mowing (avg lot)", sku: "LND-MOW", category: "Maintenance", unit: "job", unitCost: 18, markupPct: 120, taxable: true, imageQuery: "lawn mowing landscaping crew", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FisE_6IVKYI2lqCuCCdlY_%2Flawn-mowing-landscaping-crew_5.jpg", description: "Mow, trim & edge average residential lot. (~$40 USD price)" },
    { key: "labor", kind: "service", name: "Landscaping Labor (per hour)", sku: "LND-LBR", category: "Labor", unit: "hour", unitCost: 28, markupPct: 100, taxable: true, imageQuery: "landscaper working garden", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FudwzEiMQyLii5JNtfpaH_%2Flandscaper-working-garden_4.jpg", description: "Crew member hourly labor. (~$41 USD)" },
    { key: "cleanup", kind: "service", name: "Seasonal Cleanup", sku: "LND-CLN", category: "Maintenance", unit: "job", unitCost: 70, markupPct: 110, taxable: true, imageQuery: "yard cleanup leaves landscaping", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FrtEK6Bvs6w-5mjeeO4Jf7%2Fyard-cleanup-leaves-landscaping_2.jpg", description: "Spring/fall yard cleanup + haul-away. (~$155 USD price)" },
    { key: "snow", kind: "service", name: "Snow Clearing (per visit)", sku: "LND-SNOW", category: "Seasonal", unit: "job", unitCost: 25, markupPct: 120, taxable: true, imageQuery: "snow plowing driveway", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F_X6ZdEMf2Pitr0QtZVkdM%2Fsnow-plowing-driveway_2.jpg", description: "Driveway + walkway snow clearing per visit. (~$55 USD price)" },
    { key: "mulch", kind: "product", name: "Mulch (per yard)", sku: "LND-MLC", category: "Materials", unit: "each", unitCost: 32, markupPct: 80, taxable: true, imageQuery: "garden mulch pile", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fhkz-GdWJ5hOBV1MUbmE43%2Fgarden-mulch-pile_0.jpg", description: "Bulk hardwood mulch, per cubic yard. (~$24 USD cost)" },
    { key: "topsoil", kind: "product", name: "Topsoil (per yard)", sku: "LND-SOIL", category: "Materials", unit: "each", unitCost: 28, markupPct: 80, taxable: true, imageQuery: "topsoil garden bulk", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FkN3vineDPKeK4C9nhbUVX%2Ftopsoil-garden-bulk_3.jpg", description: "Screened topsoil, per cubic yard. (~$21 USD cost)" },
    { key: "sod", kind: "product", name: "Sod (per sq ft)", sku: "LND-SOD", category: "Materials", unit: "sqft", unitCost: 0.45, markupPct: 90, taxable: true, imageQuery: "sod grass roll lawn", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FLJwUEVSTZ8uFDhRu1q3gx%2Fsod-grass-roll-lawn_2.jpg", description: "Fresh turf sod, per sq ft. (~$0.34 USD/sqft cost)" },
    { key: "shrub", kind: "product", name: "Shrub / Plant (3 gal)", sku: "LND-SHB", category: "Plants", unit: "each", unitCost: 16, markupPct: 90, taxable: true, imageQuery: "potted shrub nursery plant", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FDgDomPgUcTMsXEYg8azvg%2Fpotted-shrub-nursery-plant_0.jpg", description: "3-gallon nursery shrub. (~$12 USD cost)" },
    { key: "paver", kind: "product", name: "Concrete Paver (per sq ft)", sku: "LND-PVR", category: "Hardscape", unit: "sqft", unitCost: 3.2, markupPct: 70, taxable: true, imageQuery: "concrete patio paver stone", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F5Nrf8kVKPhwkLRRt00edU%2Fconcrete-patio-paver-stone_6.jpg", description: "Interlocking concrete paver, per sq ft. (~$2.40 USD/sqft cost)" },
    { key: "icemelt", kind: "product", name: "Ice Melt (20 kg bag)", sku: "LND-ICE", category: "Consumables", unit: "each", unitCost: 12, markupPct: 90, taxable: true, imageQuery: "ice melt salt bag", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FT6lCWlMwsDahlEvMI98KO%2Fice-melt-salt-bag_1.jpg", description: "20 kg de-icing salt bag. (~$9 USD cost)" },
    { key: "asm-mulch-beds", kind: "assembly", name: "Mulch & Refresh Beds", sku: "LND-ASM-MLC", category: "Maintenance", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "garden bed mulch installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FYkqDdy4b7f2wa26rkhbJU%2Fgarden-bed-mulch-installation_0.jpg", description: "Bed refresh: mulch material + labor to spread.", components: [{ key: "mulch", qty: 3 }, { key: "labor", qty: 3 }] },
    { key: "asm-paver-patio", kind: "assembly", name: "Paver Patio (per sq ft, installed)", sku: "LND-ASM-PVR", category: "Hardscape", unit: "sqft", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "paver patio installation backyard", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FAN6mezueueme4VljP4DDI%2Fpaver-patio-installation-backyard_4.jpg", description: "Installed paver patio per sq ft: pavers, base + labor.", components: [{ key: "paver", qty: 1 }, { key: "topsoil", qty: 0.01 }, { key: "labor", qty: 0.15 }] },
  ],

  // ─────────────── COMMERCIAL CONSTRUCTION ───────────────
  construction: [
    { key: "estimate", kind: "service", name: "Project Estimate / Takeoff", sku: "CON-EST", category: "Service", unit: "job", unitCost: 120, markupPct: 90, taxable: true, imageQuery: "construction estimator blueprint", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FnBdVafzx-kqHY4FbuCfsC%2Fconstruction-estimator-blueprint_3.jpg", description: "Detailed estimate + material takeoff. (~$170 USD price)" },
    { key: "labor", kind: "service", name: "Carpenter / Laborer (per hour)", sku: "CON-LBR", category: "Labor", unit: "hour", unitCost: 42, markupPct: 100, taxable: true, imageQuery: "construction worker building site", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fr_z2Ovt4luhRWmze2_diD%2Fconstruction-worker-building-site_0.jpg", description: "Skilled trades hourly labor. (~$62 USD)" },
    { key: "supervision", kind: "service", name: "Site Supervision (per day)", sku: "CON-SUP", category: "Management", unit: "each", unitCost: 380, markupPct: 60, taxable: true, imageQuery: "construction site supervisor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FPY67XQWVaCasBz8nbjE0V%2Fconstruction-site-supervisor_5.jpg", description: "On-site supervision/PM, per day. (~$285 USD cost)" },
    { key: "studs", kind: "product", name: "Steel Stud (per piece)", sku: "CON-STD", category: "Framing", unit: "each", unitCost: 7.5, markupPct: 70, taxable: true, imageQuery: "steel framing stud construction", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F2qmS3MM1nJ1ZhRuWRqZeX%2Fsteel-framing-stud-construction_0.jpg", description: "20-ga metal framing stud, 10 ft. (~$5.60 USD cost)" },
    { key: "drywall", kind: "product", name: "Drywall Sheet (4×8, 5/8 in)", sku: "CON-DRY", category: "Materials", unit: "each", unitCost: 18, markupPct: 70, taxable: true, imageQuery: "drywall gypsum board sheets", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FNrHNlWxrKH4RvYTcpDRPM%2Fdrywall-gypsum-board-sheets_0.jpg", description: "5/8-inch Type-X gypsum board sheet. (~$13 USD cost)" },
    { key: "concrete", kind: "product", name: "Concrete (per cu yd)", sku: "CON-CNC", category: "Materials", unit: "each", unitCost: 210, markupPct: 45, taxable: true, imageQuery: "concrete pour construction", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FdYLuoEM8878xG0mFODk_8%2Fconcrete-pour-construction_2.jpg", description: "Ready-mix concrete delivered, per cubic yard. (~$157 USD cost)" },
    { key: "insulation", kind: "product", name: "Batt Insulation (R-20, bag)", sku: "CON-INS", category: "Materials", unit: "each", unitCost: 48, markupPct: 60, taxable: true, imageQuery: "fiberglass batt insulation roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FuqEQKutPkMA3jgPru96j4%2Ffiberglass-batt-insulation-roll_1.jpg", description: "R-20 fiberglass batt, ~78 sq ft bag. (~$36 USD cost)" },
    { key: "rebar", kind: "product", name: "Rebar #4 (20 ft)", sku: "CON-RBR", category: "Materials", unit: "each", unitCost: 11, markupPct: 70, taxable: true, imageQuery: "rebar steel reinforcement", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FzvHCp5PQHAVpq4BXcY4xa%2Frebar-steel-reinforcement_2.jpg", description: "#4 (1/2 in) deformed rebar, 20 ft. (~$8.20 USD cost)" },
    { key: "plywood", kind: "product", name: "Plywood Sheathing (4×8, 1/2 in)", sku: "CON-PLY", category: "Materials", unit: "each", unitCost: 42, markupPct: 60, taxable: true, imageQuery: "plywood sheathing stack", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FGTBse1-hDWs3EapoMYWjO%2Fplywood-sheathing-stack_4.jpg", description: "1/2-inch construction plywood sheet. (~$31 USD cost)" },
    { key: "fasteners", kind: "product", name: "Structural Screws (box)", sku: "CON-FST", category: "Consumables", unit: "box", unitCost: 26, markupPct: 80, taxable: true, imageQuery: "structural screws fasteners box", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fx6yR80MCfkA_iXuQS0V1U%2Fstructural-screws-fasteners-box_1.jpg", description: "Box of structural wood/metal screws. (~$19 USD cost)" },
    { key: "asm-partition", kind: "assembly", name: "Interior Partition (per ln ft)", sku: "CON-ASM-PRT", category: "Build-Out", unit: "ft", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "interior wall framing drywall", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FEB04dSYtPZqaPqcxPshW_%2Finterior-wall-framing-drywall_8.jpg", description: "Framed + drywalled partition wall per linear foot: studs, board + labor.", components: [{ key: "studs", qty: 1.5 }, { key: "drywall", qty: 0.6 }, { key: "fasteners", qty: 0.05 }, { key: "labor", qty: 0.6 }] },
    { key: "asm-slab", kind: "assembly", name: "Concrete Slab (per sq ft)", sku: "CON-ASM-SLB", category: "Concrete", unit: "sqft", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "concrete slab pour rebar", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fg0T431oQaoRt2a5809hzl%2Fconcrete-slab-pour-rebar_5.jpg", description: "Formed + poured slab per sq ft: concrete, rebar + labor.", components: [{ key: "concrete", qty: 0.012 }, { key: "rebar", qty: 0.1 }, { key: "labor", qty: 0.08 }] },
  ],

  // ─────────────── WASTE & RECYCLING ───────────────
  waste: [
    { key: "pickup", kind: "service", name: "Scheduled Pickup (per bin)", sku: "WST-PU", category: "Collection", unit: "each", unitCost: 7, markupPct: 130, taxable: true, imageQuery: "garbage truck bin pickup", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FLkvVxTEV07q6XOTtm8o2Z%2Fgarbage-truck-bin-pickup_8.jpg", description: "Routine curbside/commercial bin pickup. (~$16 USD price)" },
    { key: "labor", kind: "service", name: "Loader / Driver (per hour)", sku: "WST-LBR", category: "Labor", unit: "hour", unitCost: 30, markupPct: 90, taxable: true, imageQuery: "waste collection worker truck", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fu_cKIW50JHOhq-HyMbVap%2Fwaste-collection-worker-truck_2.jpg", description: "Collection crew hourly labor. (~$44 USD price)" },
    { key: "junk", kind: "service", name: "Junk Removal (per truck load)", sku: "WST-JNK", category: "Service", unit: "each", unitCost: 120, markupPct: 110, taxable: true, imageQuery: "junk removal truck loading", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FYws3ruWkingQBO5osGwH-%2Fjunk-removal-truck-loading_1.jpg", description: "Full-service junk removal, per truck load. (~$265 USD price)" },
    { key: "tipping", kind: "service", name: "Landfill Tipping Fee (per tonne)", sku: "WST-TIP", category: "Disposal", unit: "each", unitCost: 95, markupPct: 40, taxable: true, imageQuery: "landfill waste disposal", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FlFjR1mtH_wTXqmXTKLeMF%2Flandfill-waste-disposal_9.jpg", description: "Pass-through landfill tipping fee, per tonne. (~$71 USD cost)" },
    { key: "binsmall", kind: "product", name: "Roll-Off Bin (10 yd, rental)", sku: "WST-BIN10", category: "Equipment", unit: "each", unitCost: 180, markupPct: 90, taxable: true, imageQuery: "roll off dumpster bin small", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FKXop9SLREKrQDZW60oR0Y%2Froll-off-dumpster-bin-small_6.jpg", description: "10-yard roll-off bin, weekly rental. (~$135 USD cost)" },
    { key: "binlarge", kind: "product", name: "Roll-Off Bin (20 yd, rental)", sku: "WST-BIN20", category: "Equipment", unit: "each", unitCost: 240, markupPct: 90, taxable: true, imageQuery: "roll off dumpster bin large", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FTrt__npmnGoUC543fUxzF%2Froll-off-dumpster-bin-large_2.jpg", description: "20-yard roll-off bin, weekly rental. (~$180 USD cost)" },
    { key: "cart", kind: "product", name: "Wheeled Cart (240 L)", sku: "WST-CART", category: "Equipment", unit: "each", unitCost: 55, markupPct: 80, taxable: true, imageQuery: "240 litre wheeled waste cart", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4elEbMS5B_jfTUCjuRViE%2F240-litre-wheeled-waste-cart_6.jpg", description: "240-litre wheeled collection cart. (~$41 USD cost)" },
    { key: "compactor", kind: "product", name: "Compactor Bin (commercial)", sku: "WST-CMP", category: "Equipment", unit: "each", unitCost: 4200, markupPct: 35, taxable: true, imageQuery: "commercial waste compactor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FdH5Plk0qkiyopWQEtxKVF%2Fcommercial-waste-compactor_0.jpg", description: "Stationary commercial compactor. (~$3,150 USD cost)" },
    { key: "bags", kind: "product", name: "Heavy-Duty Bags (case)", sku: "WST-BAG", category: "Consumables", unit: "box", unitCost: 28, markupPct: 90, taxable: true, imageQuery: "heavy duty garbage bags case", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F8yN7MlPUtvMZ_MyfhGQ1d%2Fheavy-duty-garbage-bags-case_8.jpg", description: "Case of contractor-grade bags. (~$21 USD cost)" },
    { key: "recycling", kind: "service", name: "Recycling Sorting (per tonne)", sku: "WST-REC", category: "Recycling", unit: "each", unitCost: 45, markupPct: 70, taxable: true, imageQuery: "recycling sorting facility", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F3idiZN0GStbG0Ttz5lNk4%2Frecycling-sorting-facility_0.jpg", description: "Materials sorting/processing, per tonne. (~$34 USD cost)" },
    { key: "asm-binrental", kind: "assembly", name: "Bin Drop + Haul (10 yd)", sku: "WST-ASM-BIN", category: "Service", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "dumpster delivery driveway", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F6EzwEGAkjLGFqLQgh1oo-%2Fdumpster-delivery-driveway_0.jpg", description: "10-yd bin delivery, rental + one haul/tipping.", components: [{ key: "binsmall", qty: 1 }, { key: "pickup", qty: 1 }, { key: "tipping", qty: 1 }] },
    { key: "asm-cleanout", kind: "assembly", name: "Property Clean-Out", sku: "WST-ASM-CLN", category: "Service", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "property cleanout junk removal crew", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FBhj0JeBJTHoeS6j81Tk8B%2Fproperty-cleanout-junk-removal-crew_0.jpg", description: "Full clean-out: junk removal + crew labor + disposal.", components: [{ key: "junk", qty: 1 }, { key: "labor", qty: 4 }, { key: "tipping", qty: 1 }] },
  ],

  // ─────────────── UTILITY SERVICES ───────────────
  utility: [
    { key: "locate", kind: "service", name: "Utility Locate / Mark-Out", sku: "UTL-LOC", category: "Service", unit: "job", unitCost: 55, markupPct: 120, taxable: true, imageQuery: "utility locate paint markings ground", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FSHZDRnICLYFL_kf7eCg1w%2Futility-locate-paint-markings-ground_3.jpg", description: "Underground utility locate + marking. (~$120 USD price)" },
    { key: "labor", kind: "service", name: "Line Technician (per hour)", sku: "UTL-LBR", category: "Labor", unit: "hour", unitCost: 58, markupPct: 100, taxable: true, imageQuery: "utility line technician working", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fvbo4TaNI6aceMwqwF6rUQ%2Futility-line-technician-working_7.jpg", description: "Field utility technician hourly labor. (~$86 USD)" },
    { key: "meter-read", kind: "service", name: "Meter Reading / Exchange", sku: "UTL-MTR", category: "Service", unit: "each", unitCost: 18, markupPct: 110, taxable: true, imageQuery: "utility meter reading technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fh8R3ao8lVn3aRIhl45u_x%2Futility-meter-reading-technician_2.jpg", description: "Meter read or swap, per site. (~$38 USD price)" },
    { key: "meter", kind: "product", name: "Smart Meter (electric)", sku: "UTL-SMTR", category: "Equipment", unit: "each", unitCost: 95, markupPct: 60, taxable: true, imageQuery: "smart electric meter", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F40fIf7HNxPHbGdwh_aXey%2Fsmart-electric-meter_0.jpg", description: "AMI smart electric meter. (~$70 USD cost)" },
    { key: "transformer", kind: "product", name: "Pad-Mount Transformer (25 kVA)", sku: "UTL-XFM", category: "Equipment", unit: "each", unitCost: 3800, markupPct: 35, taxable: true, imageQuery: "pad mount transformer utility", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FKSZkyzf4vOn_AO4En1hWs%2Fpad-mount-transformer-utility_2.jpg", description: "25 kVA pad-mount distribution transformer. (~$2,850 USD cost)" },
    { key: "conduit", kind: "product", name: "PVC Conduit (per ft)", sku: "UTL-CND", category: "Materials", unit: "ft", unitCost: 1.1, markupPct: 90, taxable: true, imageQuery: "pvc electrical conduit pipe", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FHwNMHySjJRskAJ_FfFcZl%2Fpvc-electrical-conduit-pipe_0.jpg", description: "Schedule-40 PVC conduit, per foot. (~$0.82 USD/ft cost)" },
    { key: "cable", kind: "product", name: "URD Cable (per ft)", sku: "UTL-CBL", category: "Materials", unit: "ft", unitCost: 4.2, markupPct: 60, taxable: true, imageQuery: "underground utility cable spool", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F2hD62tFCCeS2i_lAPAeb0%2Funderground-utility-cable-spool_0.jpg", description: "Underground residential distribution cable, per ft. (~$3.13 USD/ft cost)" },
    { key: "valve", kind: "product", name: "Water Main Valve", sku: "UTL-VLV", category: "Parts", unit: "each", unitCost: 220, markupPct: 55, taxable: true, imageQuery: "water main gate valve", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FNXgGxjbc5o7QKgVneTK-N%2Fwater-main-gate-valve_3.jpg", description: "Cast-iron water main gate valve. (~$165 USD cost)" },
    { key: "hydrant", kind: "product", name: "Fire Hydrant", sku: "UTL-HYD", category: "Equipment", unit: "each", unitCost: 1650, markupPct: 40, taxable: true, imageQuery: "fire hydrant", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4IGfAp6Qgv5BcO5I1s5yz%2Ffire-hydrant_7.jpg", description: "Dry-barrel municipal fire hydrant. (~$1,235 USD cost)" },
    { key: "marker", kind: "product", name: "Utility Marker Post", sku: "UTL-MRK", category: "Materials", unit: "each", unitCost: 14, markupPct: 90, taxable: true, imageQuery: "utility marker post field", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4tDxYdsgWUjr81Mr-ye_T%2Futility-marker-post-field_0.jpg", description: "Underground utility marker post. (~$10 USD cost)" },
    { key: "asm-service-connect", kind: "assembly", name: "New Service Connection", sku: "UTL-ASM-SVC", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "utility service connection trench", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FiTOWcsbn2sceHuqZg_WMB%2Futility-service-connection-trench_2.jpg", description: "New underground service: conduit, cable, meter, locate + labor.", components: [{ key: "conduit", qty: 50 }, { key: "cable", qty: 50 }, { key: "meter", qty: 1 }, { key: "locate", qty: 1 }, { key: "labor", qty: 6 }] },
    { key: "asm-meter-swap", kind: "assembly", name: "Smart Meter Exchange", sku: "UTL-ASM-MTR", category: "Service", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "smart meter installation technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FbeHyzoBoQ-0jCl7_MvAyE%2Fsmart-meter-installation-technician_3.jpg", description: "Meter swap: new smart meter + field exchange labor.", components: [{ key: "meter", qty: 1 }, { key: "meter-read", qty: 1 }, { key: "labor", qty: 0.5 }] },
  ],

  // ─────────────── HEALTHCARE HOME SERVICES ───────────────
  healthcare: [
    { key: "visit", kind: "service", name: "Home Care Visit (per hour)", sku: "HLT-VIS", category: "Care", unit: "hour", unitCost: 26, markupPct: 110, taxable: false, imageQuery: "home care nurse patient visit", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FkG6zuxj44FQci1krWZs4U%2Fhome-care-nurse-patient-visit_1.jpg", description: "Personal support worker home visit, per hour. (~$55 USD price)" },
    { key: "nursing", kind: "service", name: "Skilled Nursing Visit", sku: "HLT-RN", category: "Care", unit: "job", unitCost: 65, markupPct: 100, taxable: false, imageQuery: "home nurse skilled visit", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F7YiyYzgpeaiGteqOJjr20%2Fhome-nurse-skilled-visit_3.jpg", description: "RN/LPN clinical home visit. (~$130 USD price)" },
    { key: "assessment", kind: "service", name: "Initial Care Assessment", sku: "HLT-ASMT", category: "Care", unit: "job", unitCost: 70, markupPct: 100, taxable: false, imageQuery: "home health assessment clipboard", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FmT_h2wZ0AhU3ElbpNBdzy%2Fhome-health-assessment-clipboard_0.jpg", description: "In-home needs assessment + care plan. (~$140 USD price)" },
    { key: "therapy", kind: "service", name: "Physiotherapy Session", sku: "HLT-PT", category: "Therapy", unit: "job", unitCost: 55, markupPct: 100, taxable: false, imageQuery: "home physiotherapy session elderly", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FGP18VGHqfwdIzf_G5smKg%2Fhome-physiotherapy-session-elderly_2.jpg", description: "In-home physiotherapy session. (~$110 USD price)" },
    { key: "wound-kit", kind: "product", name: "Wound Care Kit", sku: "HLT-WND", category: "Supplies", unit: "each", unitCost: 14, markupPct: 90, taxable: false, imageQuery: "medical wound care dressing kit", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fl8Kq-nrvkQZZkvO6c8nz1%2Fmedical-wound-care-dressing-kit_0.jpg", description: "Sterile dressing + supplies kit. (~$10 USD cost)" },
    { key: "gloves", kind: "product", name: "Nitrile Gloves (box)", sku: "HLT-GLV", category: "Supplies", unit: "box", unitCost: 9, markupPct: 90, taxable: false, imageQuery: "nitrile medical gloves box", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FzJXZDKbpDJI0PnciXCsX3%2Fnitrile-medical-gloves-box_3.jpg", description: "Box of 100 exam-grade nitrile gloves. (~$6.70 USD cost)" },
    { key: "bp-monitor", kind: "product", name: "Blood Pressure Monitor", sku: "HLT-BP", category: "Equipment", unit: "each", unitCost: 38, markupPct: 80, taxable: false, imageQuery: "blood pressure monitor cuff", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F-rrJAcj70N1xTqweMIuNc%2Fblood-pressure-monitor-cuff_0.jpg", description: "Automatic upper-arm BP monitor. (~$28 USD cost)" },
    { key: "walker", kind: "product", name: "Folding Walker", sku: "HLT-WLK", category: "Mobility", unit: "each", unitCost: 42, markupPct: 70, taxable: false, imageQuery: "folding medical walker mobility", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FKu-s29t1vRSDJQ_yT_ZHc%2Ffolding-medical-walker-mobility_1.jpg", description: "Adjustable folding walker. (~$31 USD cost)" },
    { key: "commode", kind: "product", name: "Bedside Commode", sku: "HLT-CMD", category: "Mobility", unit: "each", unitCost: 58, markupPct: 65, taxable: false, imageQuery: "bedside commode medical", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FgLn532KW7LDmHv8muW4NY%2Fbedside-commode-medical_0.jpg", description: "Adjustable steel bedside commode. (~$43 USD cost)" },
    { key: "oximeter", kind: "product", name: "Pulse Oximeter", sku: "HLT-OXI", category: "Equipment", unit: "each", unitCost: 16, markupPct: 90, taxable: false, imageQuery: "fingertip pulse oximeter", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FE9Y4j0s1zvZbbI79iUTdx%2Ffingertip-pulse-oximeter_4.jpg", description: "Fingertip SpO₂ pulse oximeter. (~$12 USD cost)" },
    { key: "asm-postop", kind: "assembly", name: "Post-Op Recovery Visit", sku: "HLT-ASM-PO", category: "Care", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "home nurse post operative care", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fs1ZQu6DKCk-94j6fkkVHV%2Fhome-nurse-post-operative-care_5.jpg", description: "Post-surgical home visit: nursing, wound kit, gloves.", components: [{ key: "nursing", qty: 1 }, { key: "wound-kit", qty: 1 }, { key: "gloves", qty: 1 }] },
    { key: "asm-mobility", kind: "assembly", name: "Mobility Setup Package", sku: "HLT-ASM-MOB", category: "Mobility", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "home mobility equipment setup", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F0B62zpTLFXF5HpKBkKiwz%2Fhome-mobility-equipment-setup_2.jpg", description: "Discharge mobility kit: walker, commode + setup assessment.", components: [{ key: "walker", qty: 1 }, { key: "commode", qty: 1 }, { key: "assessment", qty: 1 }] },
  ],

  // ─────────────── MUNICIPAL & PUBLIC WORKS ───────────────
  municipal: [
    { key: "labor", kind: "service", name: "Public Works Crew (per hour)", sku: "MUN-LBR", category: "Labor", unit: "hour", unitCost: 40, markupPct: 90, taxable: true, imageQuery: "public works crew road", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FzaJadciBETc_ia2VhrvPg%2Fpublic-works-crew-road_2.jpg", description: "Municipal works crew member hourly labor. (~$59 USD price)" },
    { key: "inspection", kind: "service", name: "Infrastructure Inspection", sku: "MUN-INSP", category: "Service", unit: "job", unitCost: 80, markupPct: 90, taxable: true, imageQuery: "infrastructure inspection municipal", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FsjBJnCDXeKs1sQYcHYFMK%2Finfrastructure-inspection-municipal_2.jpg", description: "Asset condition inspection + report. (~$150 USD price)" },
    { key: "pothole", kind: "service", name: "Pothole Repair (per patch)", sku: "MUN-POT", category: "Roads", unit: "each", unitCost: 45, markupPct: 100, taxable: true, imageQuery: "pothole repair asphalt crew", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FqX9rc_y5_hw-Xj6dJDWeg%2Fpothole-repair-asphalt-crew_2.jpg", description: "Hot-mix pothole patch, per repair. (~$90 USD price)" },
    { key: "sweeping", kind: "service", name: "Street Sweeping (per km)", sku: "MUN-SWP", category: "Roads", unit: "each", unitCost: 22, markupPct: 90, taxable: true, imageQuery: "street sweeper machine road", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FQdMbr20oyUZxbQwfnfhR_%2Fstreet-sweeper-machine-road_4.jpg", description: "Mechanical street sweeping, per km. (~$33 USD price)" },
    { key: "asphalt", kind: "product", name: "Cold-Patch Asphalt (bag)", sku: "MUN-ASP", category: "Materials", unit: "each", unitCost: 16, markupPct: 70, taxable: true, imageQuery: "cold patch asphalt bag", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FALipMoeWcYov3Jp7ILpHg%2Fcold-patch-asphalt-bag_0.jpg", description: "25 kg cold-patch asphalt bag. (~$12 USD cost)" },
    { key: "sign", kind: "product", name: "Traffic / Street Sign", sku: "MUN-SGN", category: "Signage", unit: "each", unitCost: 48, markupPct: 70, taxable: true, imageQuery: "traffic street sign aluminum", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fui45mtxALM9YiXrstrMdc%2Ftraffic-street-sign-aluminum_7.jpg", description: "Reflective aluminum traffic sign. (~$36 USD cost)" },
    { key: "signpost", kind: "product", name: "Sign Post (U-channel)", sku: "MUN-PST", category: "Signage", unit: "each", unitCost: 22, markupPct: 80, taxable: true, imageQuery: "u channel sign post galvanized", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fegj3pRvkzd2jRA17ZXBNz%2Fu-channel-sign-post-galvanized_4.jpg", description: "Galvanized U-channel sign post. (~$16 USD cost)" },
    { key: "paint", kind: "product", name: "Line-Marking Paint (pail)", sku: "MUN-PNT", category: "Materials", unit: "each", unitCost: 38, markupPct: 70, taxable: true, imageQuery: "road line marking paint pail", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fni0HppquX6pdpSiOyj72r%2Froad-line-marking-paint-pail_5.png", description: "Traffic line-marking paint, 18.9 L pail. (~$28 USD cost)" },
    { key: "barricade", kind: "product", name: "Traffic Barricade", sku: "MUN-BAR", category: "Safety", unit: "each", unitCost: 65, markupPct: 70, taxable: true, imageQuery: "traffic barricade road work", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FVbzCke6OEI40OEDuhIy5h%2Ftraffic-barricade-road-work_5.jpg", description: "Folding A-frame traffic barricade. (~$48 USD cost)" },
    { key: "cone", kind: "product", name: "Traffic Cone (28 in)", sku: "MUN-CON", category: "Safety", unit: "each", unitCost: 11, markupPct: 90, taxable: true, imageQuery: "orange traffic cone", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FUfNh_nBTpX3hbW2PzJT7p%2Forange-traffic-cone_2.jpg", description: "28-inch reflective traffic cone. (~$8.20 USD cost)" },
    { key: "asm-sign-install", kind: "assembly", name: "Sign Install (complete)", sku: "MUN-ASM-SGN", category: "Signage", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "street sign installation crew", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F8D5LngBAQDZczuVrPdr7Y%2Fstreet-sign-installation-crew_2.jpg", description: "Installed street sign: sign, post + crew labor.", components: [{ key: "sign", qty: 1 }, { key: "signpost", qty: 1 }, { key: "labor", qty: 1 }] },
    { key: "asm-pothole-crew", kind: "assembly", name: "Pothole Patch Crew Call", sku: "MUN-ASM-POT", category: "Roads", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "road repair crew pothole asphalt", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FkQWWKdM0WMITc89POkF_G%2Froad-repair-crew-pothole-asphalt_7.jpg", description: "Crew pothole repair: asphalt material, patch labor + traffic control.", components: [{ key: "asphalt", qty: 2 }, { key: "pothole", qty: 1 }, { key: "cone", qty: 4 }, { key: "labor", qty: 2 }] },
  ],
};
